Places=["Kashmir","Osaka","Hong Kong","Venice","Brazil"]
print(Places)
print(sorted(Places))
print(Places)
print(sorted(Places,reverse=True))
print(Places)
Places.reverse()
print(Places)
Places.reverse()
print(Places)
Places.sort()
print(Places)
Places.sort(reverse=True)
print(Places)

